# Generated by Django 2.0.4 on 2018-04-14 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='longitus',
            new_name='longitud',
        ),
    ]
